require('nvim-treesitter.configs').setup {
  ensure_installed = {
    "angular",
    "c_sharp",
    "css",
    "cpp",
    "cuda",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "html",
    "htmldjango",
    "java",
    "javascript",
    "json",
    "json5",
    "jsonc",
    "nginx",
    "regex",
    "sql",
    "styled",
    "typescript",
    "xml",
    -- add others as needed
  },
  auto_install = true,
  highlight = { enable = true },
}
